[[constraint]]
  name = "github.com/MorpheoOrg/morpheo-go-packages"
  branch = "master"

[[constraint]]
  name = "gopkg.in/kataras/iris.v6"
  version = "6.2.0"
  source = "https://github.com/MorpheoOrg/iris